apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poolc-staging-files
  labels:
    app.kubernetes.io/part-of: poolc-staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
