apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: poolc-staging

resources:
  - namespace.yaml
  - files-pvc.yaml
  - frontend.yaml
  - backend.yaml
  - ingress.yaml

images:
  - name: ghcr.io/poolc/poolc-fe
    newTag: staging-5e3d03c
  - name: ghcr.io/poolc/poolc-be
    newTag: staging-969049d
