apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: poolc-staging

resources:
  - namespace.yaml
  - app-secret-sealedsecret.yaml
  - files-pvc.yaml
  - frontend.yaml
  - backend.yaml
  - ingress.yaml

images:
  - name: git.poolc.org/poolc-web/frontend
    newName: git.poolc.org/poolc-web/frontend
    newTag: latest
  - name: git.poolc.org/poolc-web/backend
    newName: git.poolc.org/poolc-web/backend
    newTag: latest
