---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: monitoring
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: loki
  serviceName: loki-headless
  template:
    metadata:
      labels:
        app: loki
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - loki
              topologyKey: kubernetes.io/hostname
      containers:
        - name: loki
          image: grafana/loki:2.9.3
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/loki/loki.yaml
          ports:
            - containerPort: 3100
              protocol: TCP
            - containerPort: 7946
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/loki
              name: config
            - mountPath: /loki
              name: data
            - mountPath: /wal
              name: wal
      securityContext:
        fsGroup: 10001
        runAsUser: 10001
      volumes:
        - name: config
          configMap:
            name: loki-config
            items:
              - key: loki.yaml
                path: loki.yaml
        - name: wal
          emptyDir: {}
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: local-path
        volumeMode: Filesystem
