grafana:
  additionalDataSources:
    - access: proxy
      isDefault: false
      name: Loki
      type: loki
      url: http://loki.monitoring.svc.cluster.local:3100
  admin:
    existingSecret: kube-prometheus-stack-grafana
    userKey: admin-user
    passwordKey: admin-password
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - grafana
          topologyKey: kubernetes.io/hostname
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Viewer
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
      - mon.dev.poolc.org
    ingressClassName: nginx
    path: /
    pathType: Prefix
  replicaCount: 2
  service:
    nodePort: 30010
    type: NodePort

ingressNginx:
  controller:
    metrics:
      enabled: true
      serviceMonitor:
        scrapeInterval: 11s
  enabled: true

kube-state-metrics:
  metricLabelsAllowlist:
    - pods=[*]
  prometheus:
    monitor:
      scrapeInterval: 11s

kubelet:
  serviceMonitor:
    interval: 11s

nodeExporter:
  prometheus:
    monitor:
      scrapeInterval: 11s

prometheus:
  prometheusSpec:
    enableAdminAPI: false
    retention: 30d
    scrapeInterval: 11s
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: local-path
