---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pks-ssh-cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAHWKu+0T8iNlG+1YJCE9Fti+AUzh1H/Fr2nthJ+mn04CPaeq4Rhd87gWM7Ilx/UiD545Lh4Rkr2U7p2Oh8mJ6QTSX1UDh2ws177vL9Exx+K2FCBz3o10zUJAn1BCTG7DxT9Bq3vr7Na2d8SfteFlsK9CYyzW3hLcZ4KCNuqS60Sw1Dj/szlJSW0B+Y173uOM8vm70fGMsG9tH4n8x8OCWR6Nej0nAoYt4phoSWY3NmNnzs6L385VlxEt8buuMrbV183dUAOncabXxfl96AGpWYHP+kbAyXCCXFZmlqA5BctfmtJT6uqcYL5bJA2sQY6Wr1ky4P9QfihA4uzpQ2MnZOBzSVtflmuodNdORJvgJK99+ZGJjB3oFRDdX4XCzKR5QBhp1wPbSjuYLs1+ZFr4WPc2Xk2QQcKrrTzR17ODnEbtFkbeIJ59cIDXUseVy61lx8dV0FfWESpIg24DgS9dYwKcT5gbpSx8QJ/yj39+M2XCOjtOcDWicqFgZHhiW3v9G3pBh2mCZaLONKGyVOVOPKDRrN7zxgDc8do1Jdvp8Ai8jhJzx55yQEZohMAgIHa+SGOZ0D5u63kcyqzifLuB8y2mm5cluc2OrCFvf8SXlGW3i4ZVM9k8Fd0vlPzIKhc7h5Yjcim9LCT8LdUErOG782CIqOjyG8dXnLg3aHPcdxHsQjVIYfEkaiEKCyHt2lNsIjgXS0Gx4amb/r453hySV9aQkALQo/sZ3DsLbfUs9eVrjo7706NAFAFqK37qrv6tSH0g8quJz0ngOKnhKLgWrzgmZyCr5Tlfzf2Frrq5t1Fe43w5HrRUwMSn9yHK4q2JCYzrNnDwU5Yh7jfx7rVqd5+5eWh39co7uXuINZgGGMMg14j2ITmjmekzOrz5oB3v+6hcU+6+iCyyM+uhvgo1P3s41E/6wUXERfgkA8GJCsIA4F08KCe6WlqjtKb3eS7bxkpyIqh2oZIsJbIaInBTOrU6+btMR4qTTWtnrKH8eHYwvD4sJnomKR4+StpyQA90CN
  template:
    metadata:
      name: pks-ssh-cloudflared-token
      namespace: cloudflared
    type: Opaque
