---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-dns-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAww73AW4GJTZy4RZn386nN+cSXJQvwig3jvuMG1+KNu5F8b9L7ZIMOO+ZkzGxbCgvKaZbHulyzPGMunOY3wJcxJRKi7h6xS3aYwWq5rkgLS4JILTtN0/L1CzTkTdXngWr6bW9SyfKvOoRkdqxNrPwjrhapFQoaHA2CNcx/UwKq2qOus7v7GUtbBlT3Fp0CRPO/P5ZKaUDkEkcMTqHy9+QYBG6jgrGiFfUlCPWe2Mf5Qv+liYTZAq2WrkIcj7GIFC1CWQIthWG/LljvxsqqmzUnw7K2lRgC7dLxS9HxcShmD7fknlBnswfXYVptDbqvNz6Y02xrO+kKLRso0unWq7CIntGjPBGl9WvNWfSQuhZX4PRZcD47G8ZICWerZ20Y9NH3Nsa+lhooFE50/TI7gLv3QOtXIiWqMy2D8mfQHYgOxo+vzK4qL2e/nLHhxSFlERsNVun/MdGLeYpMElD0xACw/PEGQAao26zTxSjErE4sHHWDnP5lT1HH2h/+oqpxCxhk5mwcA5IiTjRi5aSmO0jKvETI9tmFj+wWFzDXoby61rvMlCGhnUyVmQ76DjJ5C3kLvP0t/k7BMX1AYPUTPXr+nvg5zgYy9D9+f3kambQUK0fXxXzdthqDkEpVnT8Lnm5SNvwcgZ4gGw2IBMia6rrI30M5GM3GOSH0PcjEE8SL+3KiPoR/S41Md0A6Esa2yWWy90xsdORdtI8B/Rbtjvl2jzwQttkC7wvOpvJyM1j2bBW37xnAsqw1rnGxKrFMVxZW5BPiYQ==
  template:
    metadata:
      name: cloudflare-dns-api-token
      namespace: cert-manager
    type: Opaque
