---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: route53-dns-api-credentials
  namespace: cert-manager
spec:
  encryptedData:
    access-key-id: AgBj0kYBFsTnhpQEageSglaLjyOCNcsBCpQagqQFDVBh5NzJEjClHmE0Bs0/8kl+t+y51FFzgLCvqeXOPpK7oktrs9IbjO4uMr7csu4eTa0zjmVkJteuXMjWPEjN7ziBabA288ucy7S2v9fdWqPJWYS5AzQ2zPrbLk4r/qp145bh5CNMirOoAr/wXq7lAvdAJbwNNQ5A+5MBekNnLsvTpiO/1ISxQLRMrwOQXIH9B6tTgkiA+VDXfYbsTg6kgFMBICPPJ4QFuY1yS4M8XBCn+vIKaAgdIBDqFf3iGy0eF5pkKxZm/0Txzzx+c7NkuU8kEcjyd2hPA15oJbMzVwgy80vBp8C7ASMeixT+T5hTip1LlbbbNUmtJRvxaxfHyTVg1r37jvlI1Y3ng9Nbq0BzkBmq3+/arGOlp3KuA3vIpWFGDJ8G3pVRv5ZcoCCfEHPRG4HsjaOK4/vBVIV/B7EbZdqXHuUONMiQ3nn8lr/7OCIrEt5cktcytDBmZWXGWJFApk87agJfHEmiYa//CrJ7BuBTdQvc0Jx1YsTUyZhNd925ecV3Vlp+3kwTTlHB0T+0TLOgcOQj38C8FAOJCOyDg+DvYBeU0GajMP4zFNZvjYa1myCv7zpieFung3EVLUs+9TvdxLBDFSK/tKcrwm6RYWKl/YGozPgUhqiJzZyiAyRdSH8nRZYHbPHT9L6wRouxtft5RxgOkruQAmidpixMP0/kbCMcpg==
    secret-access-key: AgAbuFtRgLqoV1/8cnEYy0ReLsuGCovuftu5Z0kZJ0vrcLOPtlGJ3A3aGA/yvvAjJaO/VEOuoq7YguD1WcVcGBIPuMt2KTUQTn8+EE3K7/ppYEHX6+hsRnJZSLeXcdChtc8a5g4I7+7+hfcA8Hkd5Fnx4pkRD9bN4N/AC+fTwCTdl4+8QKflV3AHS6zqmxPdRHFMMd5Kz8pcDSc1ug75v6vPCdCx1ZTpUN9RH013ShuxvX3f8pxZ0vd0jx0fXVUX5O/SNzx5I06iLdjlPiwoRwn5oynNZrknRSeQr70kL6KHM5xhKrMNnsgRh3AZmd8CnOfgP9VZsxYrNKeWpY0pZSi9WQl8t583dAF9g5WdepxGuWumg/jgCMlabXPUKl5UGafu54Tnbzw/o7/xuvsUd0iskxb0y907LCV169zDqwIQlMeUTODnb6mS0ru5Zz3J1Qh5ZO0cRRpO4CcWcho81Oc5HNmCcaNGT68VIrUtNZgW2EQA1WCIMMZQvzzoUKcPHvFM4E4+Fyh1b5jEP892jqam9tRdymf26vyRORHt/oOBkt8fdcGuwxHNcbQlmhUoAn1CTg6+WM/mqQK+MZqOkR/+7Pk8EawFwvoIfYgD5hg5R8uaFIhtOcUh+TPEaHurAWTVLfO2uETgCMk3e5I5+EKVHaXPG8dMC7gugdRnStCP6hEhWgRH2GmpU7EvrDKsk+2fDqqeW6HoRLYRVp0VRSWS1I9qd3qfck70avqUyDa/5cQ5RYz4Dati
  template:
    metadata:
      name: route53-dns-api-credentials
      namespace: cert-manager
    type: Opaque
