name: Credentials Updater

on:
  pull_request:
    paths:
      - services/credentials-updater/**
      - .github/workflows/credentials-updater.yml
  push:
    branches: [main]
    paths:
      - services/credentials-updater/**
      - .github/workflows/credentials-updater.yml

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/credentials-updater
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: services/credentials-updater/go.mod
      - run: go test ./...
